// Generated by @wagmi/cli@1.1.0 on 2/18/2024 at 8:01:28 AM
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GateKeeper
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const gateKeeperABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: '_semaphore', internalType: 'address', type: 'address' },
      { name: '_verifier', internalType: 'address', type: 'address' },
      { name: '_repoNameChunk1', internalType: 'uint256', type: 'uint256' },
      { name: '_repoNameChunk2', internalType: 'uint256', type: 'uint256' }
    ]
  },
  { type: 'error', inputs: [], name: 'CommitmentExists' },
  { type: 'error', inputs: [], name: 'EmailAlreadyRegistered' },
  { type: 'error', inputs: [], name: 'InvalidProof' },
  { type: 'error', inputs: [], name: 'InvalidRepository' },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'CONTRIBUTORS_GROUP_ID',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'admin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'emailNullifier',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'groth16verifier',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'commitment', internalType: 'uint256', type: 'uint256' }],
    name: 'isContributor',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' }
    ],
    name: 'isMember',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'proof',
        internalType: 'struct IGateKeeperMeta.Proof',
        type: 'tuple',
        components: [
          { name: '_pA', internalType: 'uint256[2]', type: 'uint256[2]' },
          { name: '_pB', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
          { name: '_pC', internalType: 'uint256[2]', type: 'uint256[2]' },
          {
            name: '_pubSignals',
            internalType: 'uint256[5]',
            type: 'uint256[5]'
          }
        ]
      }
    ],
    name: 'joinContributors',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'repository',
    outputs: [
      { name: 'chunk1', internalType: 'uint256', type: 'uint256' },
      { name: 'chunk2', internalType: 'uint256', type: 'uint256' }
    ]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'semaphore',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_admin', internalType: 'address', type: 'address' }],
    name: 'setAdmin',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_repoNameChunk1', internalType: 'uint256', type: 'uint256' },
      { name: '_repoNameChunk2', internalType: 'uint256', type: 'uint256' }
    ],
    name: 'setRepositoryName',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_semaphore', internalType: 'address', type: 'address' }],
    name: 'setSemaphore',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_verifier', internalType: 'address', type: 'address' }],
    name: 'setVerifier',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalContributors',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalDonators',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'signal',
        internalType: 'struct IGateKeeperMeta.Signal',
        type: 'tuple',
        components: [
          { name: 'signal', internalType: 'uint256', type: 'uint256' },
          { name: 'scope', internalType: 'uint256', type: 'uint256' },
          { name: 'merkleTreeRoot', internalType: 'uint256', type: 'uint256' },
          { name: 'nullifierHash', internalType: 'uint256', type: 'uint256' },
          { name: 'proof', internalType: 'uint256[8]', type: 'uint256[8]' }
        ]
      }
    ],
    name: 'validateContributorSignal',
    outputs: []
  }
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ZkBill
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const zkBillABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: '_gateKeeper', internalType: 'address', type: 'address' },
      { name: '_token', internalType: 'address', type: 'address' },
      { name: '_maxRefund', internalType: 'uint256', type: 'uint256' },
      { name: '_verifier', internalType: 'address', type: 'address' }
    ]
  },
  { type: 'error', inputs: [], name: 'InvalidProof' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'contributor',
        internalType: 'address',
        type: 'address',
        indexed: true
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false
      }
    ],
    name: 'Claimed'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newScopeSeed',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false
      }
    ],
    name: 'ScopeRefreshed'
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: 'gateKeeperProof',
        internalType: 'struct ZkBill.GateKeeperProof',
        type: 'tuple',
        components: [
          { name: 'merkleTreeRoot', internalType: 'uint256', type: 'uint256' },
          { name: 'nullifierHash', internalType: 'uint256', type: 'uint256' },
          { name: 'proof', internalType: 'uint256[8]', type: 'uint256[8]' }
        ]
      },
      {
        name: 'proof',
        internalType: 'struct ZkBill.Proof',
        type: 'tuple',
        components: [
          { name: '_pA', internalType: 'uint256[2]', type: 'uint256[2]' },
          { name: '_pB', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
          { name: '_pC', internalType: 'uint256[2]', type: 'uint256[2]' },
          {
            name: '_pubSignals',
            internalType: 'uint256[4]',
            type: 'uint256[4]'
          }
        ]
      }
    ],
    name: 'claim',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'gateKeeper',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getScope',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'groth16verifier',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'lastScopeRefreshTimestamp',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'maxRefund',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'refreshScope',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'scopeSeed',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'token',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  }
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__.
 */
export function useGateKeeperRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"CONTRIBUTORS_GROUP_ID"`.
 */
export function useGateKeeperContributorsGroupId<
  TFunctionName extends 'CONTRIBUTORS_GROUP_ID',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'CONTRIBUTORS_GROUP_ID',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"admin"`.
 */
export function useGateKeeperAdmin<
  TFunctionName extends 'admin',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'admin',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"emailNullifier"`.
 */
export function useGateKeeperEmailNullifier<
  TFunctionName extends 'emailNullifier',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'emailNullifier',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"groth16verifier"`.
 */
export function useGateKeeperGroth16verifier<
  TFunctionName extends 'groth16verifier',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'groth16verifier',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"isContributor"`.
 */
export function useGateKeeperIsContributor<
  TFunctionName extends 'isContributor',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'isContributor',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"isMember"`.
 */
export function useGateKeeperIsMember<
  TFunctionName extends 'isMember',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'isMember',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"repository"`.
 */
export function useGateKeeperRepository<
  TFunctionName extends 'repository',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'repository',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"semaphore"`.
 */
export function useGateKeeperSemaphore<
  TFunctionName extends 'semaphore',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'semaphore',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"totalContributors"`.
 */
export function useGateKeeperTotalContributors<
  TFunctionName extends 'totalContributors',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'totalContributors',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"totalDonators"`.
 */
export function useGateKeeperTotalDonators<
  TFunctionName extends 'totalDonators',
  TSelectData = ReadContractResult<typeof gateKeeperABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: gateKeeperABI,
    functionName: 'totalDonators',
    ...config
  } as UseContractReadConfig<typeof gateKeeperABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__.
 */
export function useGateKeeperWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          string
        >['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof gateKeeperABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, TFunctionName, TMode>({
    abi: gateKeeperABI,
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"joinContributors"`.
 */
export function useGateKeeperJoinContributors<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'joinContributors'
        >['request']['abi'],
        'joinContributors',
        TMode
      > & { functionName?: 'joinContributors' }
    : UseContractWriteConfig<
        typeof gateKeeperABI,
        'joinContributors',
        TMode
      > & {
        abi?: never
        functionName?: 'joinContributors'
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, 'joinContributors', TMode>({
    abi: gateKeeperABI,
    functionName: 'joinContributors',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setAdmin"`.
 */
export function useGateKeeperSetAdmin<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'setAdmin'
        >['request']['abi'],
        'setAdmin',
        TMode
      > & { functionName?: 'setAdmin' }
    : UseContractWriteConfig<typeof gateKeeperABI, 'setAdmin', TMode> & {
        abi?: never
        functionName?: 'setAdmin'
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, 'setAdmin', TMode>({
    abi: gateKeeperABI,
    functionName: 'setAdmin',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setRepositoryName"`.
 */
export function useGateKeeperSetRepositoryName<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'setRepositoryName'
        >['request']['abi'],
        'setRepositoryName',
        TMode
      > & { functionName?: 'setRepositoryName' }
    : UseContractWriteConfig<
        typeof gateKeeperABI,
        'setRepositoryName',
        TMode
      > & {
        abi?: never
        functionName?: 'setRepositoryName'
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, 'setRepositoryName', TMode>({
    abi: gateKeeperABI,
    functionName: 'setRepositoryName',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setSemaphore"`.
 */
export function useGateKeeperSetSemaphore<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'setSemaphore'
        >['request']['abi'],
        'setSemaphore',
        TMode
      > & { functionName?: 'setSemaphore' }
    : UseContractWriteConfig<typeof gateKeeperABI, 'setSemaphore', TMode> & {
        abi?: never
        functionName?: 'setSemaphore'
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, 'setSemaphore', TMode>({
    abi: gateKeeperABI,
    functionName: 'setSemaphore',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setVerifier"`.
 */
export function useGateKeeperSetVerifier<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'setVerifier'
        >['request']['abi'],
        'setVerifier',
        TMode
      > & { functionName?: 'setVerifier' }
    : UseContractWriteConfig<typeof gateKeeperABI, 'setVerifier', TMode> & {
        abi?: never
        functionName?: 'setVerifier'
      } = {} as any
) {
  return useContractWrite<typeof gateKeeperABI, 'setVerifier', TMode>({
    abi: gateKeeperABI,
    functionName: 'setVerifier',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"validateContributorSignal"`.
 */
export function useGateKeeperValidateContributorSignal<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof gateKeeperABI,
          'validateContributorSignal'
        >['request']['abi'],
        'validateContributorSignal',
        TMode
      > & { functionName?: 'validateContributorSignal' }
    : UseContractWriteConfig<
        typeof gateKeeperABI,
        'validateContributorSignal',
        TMode
      > & {
        abi?: never
        functionName?: 'validateContributorSignal'
      } = {} as any
) {
  return useContractWrite<
    typeof gateKeeperABI,
    'validateContributorSignal',
    TMode
  >({
    abi: gateKeeperABI,
    functionName: 'validateContributorSignal',
    ...config
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__.
 */
export function usePrepareGateKeeperWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, TFunctionName>,
    'abi'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"joinContributors"`.
 */
export function usePrepareGateKeeperJoinContributors(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, 'joinContributors'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'joinContributors',
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, 'joinContributors'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setAdmin"`.
 */
export function usePrepareGateKeeperSetAdmin(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setAdmin'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'setAdmin',
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setAdmin'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setRepositoryName"`.
 */
export function usePrepareGateKeeperSetRepositoryName(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setRepositoryName'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'setRepositoryName',
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setRepositoryName'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setSemaphore"`.
 */
export function usePrepareGateKeeperSetSemaphore(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setSemaphore'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'setSemaphore',
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setSemaphore'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"setVerifier"`.
 */
export function usePrepareGateKeeperSetVerifier(
  config: Omit<
    UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setVerifier'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'setVerifier',
    ...config
  } as UsePrepareContractWriteConfig<typeof gateKeeperABI, 'setVerifier'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link gateKeeperABI}__ and `functionName` set to `"validateContributorSignal"`.
 */
export function usePrepareGateKeeperValidateContributorSignal(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof gateKeeperABI,
      'validateContributorSignal'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: gateKeeperABI,
    functionName: 'validateContributorSignal',
    ...config
  } as UsePrepareContractWriteConfig<
    typeof gateKeeperABI,
    'validateContributorSignal'
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__.
 */
export function useZkBillRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any
) {
  return useContractRead({ abi: zkBillABI, ...config } as UseContractReadConfig<
    typeof zkBillABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"gateKeeper"`.
 */
export function useZkBillGateKeeper<
  TFunctionName extends 'gateKeeper',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'gateKeeper',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"getScope"`.
 */
export function useZkBillGetScope<
  TFunctionName extends 'getScope',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'getScope',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"groth16verifier"`.
 */
export function useZkBillGroth16verifier<
  TFunctionName extends 'groth16verifier',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'groth16verifier',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"lastScopeRefreshTimestamp"`.
 */
export function useZkBillLastScopeRefreshTimestamp<
  TFunctionName extends 'lastScopeRefreshTimestamp',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'lastScopeRefreshTimestamp',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"maxRefund"`.
 */
export function useZkBillMaxRefund<
  TFunctionName extends 'maxRefund',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'maxRefund',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"scopeSeed"`.
 */
export function useZkBillScopeSeed<
  TFunctionName extends 'scopeSeed',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'scopeSeed',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"token"`.
 */
export function useZkBillToken<
  TFunctionName extends 'token',
  TSelectData = ReadContractResult<typeof zkBillABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: zkBillABI,
    functionName: 'token',
    ...config
  } as UseContractReadConfig<typeof zkBillABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link zkBillABI}__.
 */
export function useZkBillWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof zkBillABI, string>['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof zkBillABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<typeof zkBillABI, TFunctionName, TMode>({
    abi: zkBillABI,
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"claim"`.
 */
export function useZkBillClaim<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof zkBillABI, 'claim'>['request']['abi'],
        'claim',
        TMode
      > & { functionName?: 'claim' }
    : UseContractWriteConfig<typeof zkBillABI, 'claim', TMode> & {
        abi?: never
        functionName?: 'claim'
      } = {} as any
) {
  return useContractWrite<typeof zkBillABI, 'claim', TMode>({
    abi: zkBillABI,
    functionName: 'claim',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"refreshScope"`.
 */
export function useZkBillRefreshScope<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof zkBillABI,
          'refreshScope'
        >['request']['abi'],
        'refreshScope',
        TMode
      > & { functionName?: 'refreshScope' }
    : UseContractWriteConfig<typeof zkBillABI, 'refreshScope', TMode> & {
        abi?: never
        functionName?: 'refreshScope'
      } = {} as any
) {
  return useContractWrite<typeof zkBillABI, 'refreshScope', TMode>({
    abi: zkBillABI,
    functionName: 'refreshScope',
    ...config
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link zkBillABI}__.
 */
export function usePrepareZkBillWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof zkBillABI, TFunctionName>,
    'abi'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: zkBillABI,
    ...config
  } as UsePrepareContractWriteConfig<typeof zkBillABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"claim"`.
 */
export function usePrepareZkBillClaim(
  config: Omit<
    UsePrepareContractWriteConfig<typeof zkBillABI, 'claim'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: zkBillABI,
    functionName: 'claim',
    ...config
  } as UsePrepareContractWriteConfig<typeof zkBillABI, 'claim'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link zkBillABI}__ and `functionName` set to `"refreshScope"`.
 */
export function usePrepareZkBillRefreshScope(
  config: Omit<
    UsePrepareContractWriteConfig<typeof zkBillABI, 'refreshScope'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: zkBillABI,
    functionName: 'refreshScope',
    ...config
  } as UsePrepareContractWriteConfig<typeof zkBillABI, 'refreshScope'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link zkBillABI}__.
 */
export function useZkBillEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof zkBillABI, TEventName>,
    'abi'
  > = {} as any
) {
  return useContractEvent({
    abi: zkBillABI,
    ...config
  } as UseContractEventConfig<typeof zkBillABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link zkBillABI}__ and `eventName` set to `"Claimed"`.
 */
export function useZkBillClaimedEvent(
  config: Omit<
    UseContractEventConfig<typeof zkBillABI, 'Claimed'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: zkBillABI,
    eventName: 'Claimed',
    ...config
  } as UseContractEventConfig<typeof zkBillABI, 'Claimed'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link zkBillABI}__ and `eventName` set to `"ScopeRefreshed"`.
 */
export function useZkBillScopeRefreshedEvent(
  config: Omit<
    UseContractEventConfig<typeof zkBillABI, 'ScopeRefreshed'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: zkBillABI,
    eventName: 'ScopeRefreshed',
    ...config
  } as UseContractEventConfig<typeof zkBillABI, 'ScopeRefreshed'>)
}
